### ISSUE TITLE
Theme upgrade from dmponline fails at upgrade:theme_transform

### ISSUE THREAD

**Issue by MinkaKaraivanova** [DMPRoadmap/roadmap#1487]
Following theme migration procedure from
https://github.com/DMPRoadmap/roadmap/wiki/Themes#migrating-from-dmponlinev4

Following step fails:
`rake upgrade:theme_transform`

with output
```
NoMethodError: undefined method `title' for nil:NilClass
/home/dmp/DMProadmap/lib/tasks/upgrade.rake:213:in `block (4 levels) in <top (required)>'
/home/dmp/DMProadmap/lib/tasks/upgrade.rake:210:in `each'
/home/dmp/DMProadmap/lib/tasks/upgrade.rake:210:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.7/lib/active_record/transactions.rb:220:in `transaction'
/home/dmp/DMProadmap/lib/tasks/upgrade.rake:181:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => upgrade:theme_transform
(See full trace by running task with --trace)
W, [2018-05-13T21:48:22.258856 #30975]  WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /var/lib/gems/2.3.0/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
```

**Comment by vyruss** [comment]
Cannot replicate. We have migrated multiple databases successfully using the same scripts. This looks like a data issue (your database may be missing one/some of the themes in the list beginning at line 182)?

Format is: `{'<new theme name>':'<old theme name>'},` like: `{'Data description':'Data Type'},`

**Comment by MinkaKaraivanova** [comment]
Thanks!

You are right. Problem was in the data. One theme was renamed. When restoring the title to its original name, upgrade task work fine!
