### ISSUE TITLE
Issue with the database seed file

### ISSUE THREAD

**Issue by Sudiukil** [DMPRoadmap/roadmap#1816]
[1]: https://github.com/DMPRoadmap/roadmap/wiki/Installation
[2]: https://github.com/DMPRoadmap/roadmap/blob/c1cc022ae185651973b979f0d2a5a382e9cc4a62/db/migrate/20180405151713_rename_template_fields.rb#L3-L4

When following the [installation instructions][1], the user is told to run the `rake db:seed` command. Doing so raise an error.

**Expected behaviour:**

The user should be able to run `rake db:seed` without any issues.

**Actual behaviour:**

Running `rake db:seed` raises the following error:

```
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes for Template: migrated, dmptemplate_id
/home/quentin/.rvm/gems/ruby-2.4.4/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security/sanitizer.rb:60:in `process_removed_attributes'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security/sanitizer.rb:10:in `sanitize'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/protected_attributes-1.1.3/lib/active_model/mass_assignment_security.rb:352:in `sanitize_for_mass_assignment'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/attribute_assignment.rb:58:in `assign_attributes'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/activerecord-4.2.10/lib/active_record/core.rb:281:in `initialize'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/validations.rb:15:in `create!'
/home/quentin/Projets/roadmap/db/seeds.rb:386:in `block in <top (required)>'
/home/quentin/Projets/roadmap/db/seeds.rb:384:in `map'
/home/quentin/Projets/roadmap/db/seeds.rb:384:in `<top (required)>'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/home/quentin/.rvm/gems/ruby-2.4.4/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/quentin/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:15:in `eval'
/home/quentin/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Steps to reproduce:**

Follow the [installation instructions][1] up to the point where the user is supposed to run `rake db:seed`.

**Potential fix:**

It would seem the columns causing the error ('migrated' and 'dmptemplate_id') were [renamed][2], the seed file should be changed accordingly.

**Comment by Yu-Chieh-Henry-Yang** [comment]
I face the same issue

**Comment by Bodacious** [comment]
Hi all,

We've updated the seeds file and added a stage to the Travis CI script to check the seeds with each push.

These changes are currently on `development`. Please bear with us while we finalise changes for the next release version on `master`

**Comment by magdalenadrafiova** [comment]
@briri and @xsrust is still still relevant?

**Comment by briri** [comment]
Yes. this has been addressed
