### ISSUE TITLE
Missing paginable method

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1906]
Please complete the following fields as applicable:

**Expected behaviour:**
The 'My Dashboard' page loads after logging in

**Actual behaviour:**
The following error appears:
```shell
ActionView::Template::Error (undefined method `paginable_base_url_with_query_params' for #<#<Class:0x00007fe8d4a774d8>:0x00007fe8d46ef9a0>):
    1: <% # locals: { search_term } %>
    2: <%= form_tag(paginable_base_url_with_query_params(page: 1), method: :get, remote: true, class: 'form-inline paginable-action') do %>
    3:   <div class="form-group">
    4:     <div class="input-group">
    5:       <span class="input-group-addon" id="search-addon">
  app/views/shared/_search.html.erb:2:in `_app_views_shared__search_html_erb___4014368034944751214_47210137342900'
  /appsactionview (4.2.10) lib/action_view/template.rb:145:in `block in render'
  /appsactivesupport (4.2.10) lib/active_support/notifications.rb:166:in `instrument'
  /appsactionview (4.2.10) lib/action_view/template.rb:333:in `instrument'
  /appsactionview (4.2.10) lib/action_view/template.rb:143:in `render'
  /appsactionview (4.2.10) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  /appsactionview (4.2.10) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  /appsactionview (4.2.10) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
```

**Steps to reproduce:**
Log in

**Comment by briri** [comment]
This was patched earlier on roadmap-stg. Just verified that the My Dashboard page loads properly still.
